### PR TITLE
Add MCU_MAXTEMP_ERR

### PR DESCRIPTION
**Pull request by tomasjakubik**

### CODE REVIEW

**Comment by davidnovacek** [comment]
not sure if we want to propagate string value about specific name of MCU for MINI, MK4 and iX since they have only one MCU

**Comment by tomasjakubik** [comment]
I thought about that, but the code would be more complicated as it would have to know if this printer has `%s` or doesn't. Seems like an opportunity for error. Also I think that iX has MCU in modular bed.

**Comment by davidnovacek** [comment]
would it be better to add verb to "MCU in %s overheated."?
so it will be "MCU in %s is overheated."

**Comment by davidnovacek** [comment]
yeah you are correct about that so lets leave it universal

**Review by davidnovacek — APPROVED** [review]

**Pull request merged**
